### PR TITLE
Change routes and tests appropriately

### LINKED ISSUE #2: Adjust Root to Redirect to ‘/reminders’
When the user visits the root of the application, they should be redirected to '/reminders' and should see a list of all reminders on the page. This means making a hopefully small adjustment to your router.js file.

**Hot Tip**: This will make your previous test fail (if you had it passing). Make the necessary changes in the test(s).

### PR DESCRIPTION
**Pull request by bekahlundy**
## Purpose
When the user visits the root of the application, they should be redirected to '/reminders' and should see a list of all reminders on the page. This means making a hopefully small adjustment to your router.js file.

[Issue #2](https://github.com/turingschool-projects/1610-remember-1/issues/2)

## Approach
Changed the index route and used "beforeModel" to redirect '/' to '/reminders'

### Learning

We read the docs to find out how to do this and found a great tutorial.

[Ember Routes and Templates ](https://guides.emberjs.com/v2.11.0/tutorial/routes-and-templates/)

### Open Questions and Pre-Merge TODOs

- [x] change index route file
- [x] change test routes to make them pass

### Test coverage 

Changed the path in our tests so that it would pass again

### Follow-up tasks

- [Issue #3](https://github.com/turingschool-projects/1610-remember-1/issues/3)

#### Before
screen shot 2017-02-09 at 4 42 27 pm

#### After
screen shot 2017-02-09 at 5 46 08 pm

screen shot 2017-02-09 at 5 50 21 pm

close #2

### CODE REVIEW

File: tests/acceptance/reminder-list-test.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ test('viewing the homepage', function(assert) {
   visit('/');
 
   andThen(function() {
-    assert.equal(currentURL(), '/', 'curren turl is root');
+    assert.equal(currentURL(), '/reminders', 'current url is /reminders');
```
Comment (martensonbj) [inline tests/acceptance/reminder-list-test.js:16]: 👍

**Review by martensonbj — CHANGES_REQUESTED** [review]
Only part thats missing is removing the `{path: '/'}` bit now because we no longer ever need it to show the root in the URL.

**Comment by bekahlundy** [comment]
@martensonbj Got it. We had that changed, but I guess it didn't push up the way that we had hoped. Thanks again for all the help tonight!

**Review by martensonbj — APPROVED** [review]
